CREATE DATABASE BUGS;
USE BUGS;

CREATE TABLE USERS (
    USERID VARCHAR(32) PRIMARY KEY,
    FULL_NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(12) NOT NULL
);

CREATE TABLE USER_PRINT_HISTORY (
    PRINT_ID VARCHAR(64) PRIMARY KEY,
    USERID VARCHAR(32) NOT NULL,
    PRINT_DATE DATE NOT NULL,
    PRINT_TIME TIME NOT NULL,
    PRINTED_PAGES INT NOT NULL
);             

CREATE TABLE USER_VERIFICATION (
    USERID VARCHAR(32) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    OTP_ATTEMPTS INT NOT NULL DEFAULT 0 CHECK (OTP_ATTEMPTS <= 3),
    LAST_OTP_ATTEMPT DATETIME
);

CREATE TABLE SUCCESSFUL_LOGINS (
    LOGIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USERID VARCHAR(32) NOT NULL,
    LOGIN_TIME DATETIME NOT NULL
);

CREATE TABLE PAYMENT_HISTORY (
    PAYMENT_ID VARCHAR(64) PRIMARY KEY,
    USERID VARCHAR(32) NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    PAYMENT_TIME TIME NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL
);